apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobee-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: jobee-deploy
  template:
    metadata:
      name: my-deploy
      labels:
        app: jobee-deploy
    spec:
      volumes:
      - name: pvol
        persistentVolumeClaim :
          claimName: jobee-pvc
      containers:
        - image: hak1550/jobee:v1
          name: container1
          imagePullPolicy: IfNotPresent
          volumeMounts :
          - name: pvol
            mountPath: /data
          ports:
          - containerPort : 80
          readinessProbe:
            httpGet:
              port: 80
              path: /
          livenessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 2
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 15

